-- CyberTools Hub Database Schema

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    is_verified BOOLEAN DEFAULT FALSE,
    verification_token VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Logs table
CREATE TABLE IF NOT EXISTS logs (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    tool VARCHAR(50) NOT NULL,
    target VARCHAR(255) NOT NULL,
    result TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index on logs for faster queries
CREATE INDEX IF NOT EXISTS idx_logs_user_id ON logs(user_id);
CREATE INDEX IF NOT EXISTS idx_logs_tool ON logs(tool);
CREATE INDEX IF NOT EXISTS idx_logs_created_at ON logs(created_at);

-- Blacklist table (IP blacklist)
CREATE TABLE IF NOT EXISTS blacklist (
    id SERIAL PRIMARY KEY,
    ip VARCHAR(45) UNIQUE NOT NULL,
    reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(id)
);

-- Settings table
CREATE TABLE IF NOT EXISTS settings (
    key VARCHAR(100) PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default settings
INSERT INTO settings (key, value) VALUES 
    ('site_title', 'CyberTools Hub'),
    ('maintenance_mode', 'false'),
    ('port_scanner', 'true'),
    ('dns_lookup', 'true'),
    ('whois', 'true'),
    ('ping', 'true'),
    ('geo_ip', 'true'),
    ('ssl_check', 'true'),
    ('ads_hero', 'true'),
    ('ads_sidebar', 'true'),
    ('ads_footer', 'true')
ON CONFLICT (key) DO NOTHING;

-- Create default admin user (password: admin123)
-- Hash will be generated by the application
INSERT INTO users (username, email, password_hash, role, is_verified) 
VALUES ('admin', 'admin@cybertoolshub.com', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.VTtdY6X8v6Yq0i', 'admin', true)
ON CONFLICT (username) DO NOTHING;
